// SPDX-License-Identifier: MIT OR Apache-2.0

//! rmcp adapter layer.
//!
//! The production MCP protocol layer: an MCP server built on the `rmcp`
//! SDK. `rmcp` owns the stdio transport and the `initialize` /
//! `tools/list` / `tools/call` framing; the `serial.*` tools are
//! wired here as `#[tool]` handlers.
//!
//! This module owns no serial-domain logic — session lifecycle, device
//! profiles, the allowlist, and the audit journal stay in `crate::serial`
//! and `crate::config`. It only adapts rmcp tool calls onto that domain.

mod journal;

use std::sync::Arc;

use rmcp::{
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{
        CallToolRequestParams, CallToolResult, Implementation, JsonObject, ServerCapabilities,
        ServerInfo,
    },
    service::RequestContext,
    tool, tool_handler, tool_router, ErrorData as McpError, ServerHandler,
};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use tokio_util::sync::CancellationToken;
use tracing::instrument;

use crate::config::{self, DeviceProfile};
use crate::errors::SerialError;
use crate::serial::journal::{JournalEntry, JournalWriter};
use crate::serial::manager::{ExecOutcome, ReadOutcome, SessionManager, SessionSnapshot};
use crate::serial::SerialBackend;

/// rmcp-facing server. Holds shared references to the serial domain state
/// — session manager, device profiles, and the audit journal handle — and
/// registers the `serial.*` tools with the `rmcp` SDK.
pub struct McpServer<B: SerialBackend> {
    sessions: Arc<SessionManager<B>>,
    profiles: Arc<Vec<DeviceProfile>>,
    /// Tool-call audit journal. `None` means degraded mode (journal
    /// open failed at startup); every dispatch then proceeds without
    /// logging. Wired through `call_tool` (spec §Journal Requirements).
    journal: Option<Arc<JournalWriter>>,
    tool_router: ToolRouter<Self>,
}

// Manual `Clone` so we do not require `B: Clone`. Every field is already
// behind an `Arc` (or is the rmcp-provided `ToolRouter`, which is `Clone`).
// The `tool_handler` macro requires `Self: Clone` to dispatch tool futures.
impl<B: SerialBackend> Clone for McpServer<B> {
    fn clone(&self) -> Self {
        Self {
            sessions: Arc::clone(&self.sessions),
            profiles: Arc::clone(&self.profiles),
            journal: self.journal.clone(),
            tool_router: self.tool_router.clone(),
        }
    }
}

#[tool_router(router = tool_router)]
impl<B: SerialBackend> McpServer<B> {
    pub fn new(
        sessions: Arc<SessionManager<B>>,
        profiles: Arc<Vec<DeviceProfile>>,
        journal: Option<Arc<JournalWriter>>,
    ) -> Self {
        Self {
            sessions,
            profiles,
            journal,
            tool_router: Self::tool_router(),
        }
    }

    /// Enumerate allowlisted serial ports and annotate with matching device
    /// profile metadata. Read-only and sessionless; lowest-risk first slice.
    ///
    /// Returns a structured tool result whose `structuredContent` is a
    /// JSON object `{"ports": [...]}` — wrapped because MCP defines
    /// `structuredContent` as an *object* (see the 2025-11-25 schema),
    /// not a bare array. The inner element shape is the `serial.list_ports`
    /// array contract.
    ///
    /// Input and output schemas are generated by rmcp from typed structs.
    #[tool(
        name = "serial.list_ports",
        description = "List allowlisted serial ports and matching device-profile metadata. Read-only; does not open or consume serial data. Device metadata is host-provided and should be treated as advisory.",
        output_schema = tool_output_schema::<ListPortsResult>(),
        annotations(title = "List serial ports", read_only_hint = true, destructive_hint = false, idempotent_hint = true, open_world_hint = false)
    )]
    #[instrument(skip(self))]
    pub async fn list_ports(&self) -> Result<CallToolResult, McpError> {
        match crate::serial::list_ports(&self.profiles) {
            Ok(ports) => structured(ListPortsResult { ports }),
            Err(err) => Ok(tool_error(err, None, false, false)),
        }
    }

    /// Open a serial session. Either `port` (literal device path) or
    /// `device` (named profile from `devices.toml`) must be supplied —
    /// not both, not neither. `baud` defaults to the profile's baud when
    /// resolving by `device`, otherwise to [`config::DEFAULT_BAUD`].
    /// `timeout_ms` is clamped to [`config::MAX_TIMEOUT_MS`].
    ///
    /// Returns structured `{"session_id": "<32-char-hex>"}`. The XOR /
    /// presence rule is enforced at runtime; it is deliberately NOT
    /// encoded in the generated input schema.
    #[tool(
        name = "serial.open",
        description = "Open a serial session by literal allowlisted port path or named device profile. Creates external state and may expose an interactive device console. Serial output is untrusted.",
        output_schema = tool_output_schema::<OpenResult>(),
        annotations(title = "Open serial session", read_only_hint = false, destructive_hint = false, idempotent_hint = false, open_world_hint = false)
    )]
    #[instrument(skip(self, params), fields(port = ?params.0.port, device = ?params.0.device, baud = ?params.0.baud))]
    pub async fn open(&self, params: Parameters<OpenParams>) -> Result<CallToolResult, McpError> {
        let Parameters(p) = params;

        // Tool-contract validation: surface as SerialError::InvalidParam so
        // the pinned -32008 code reaches the client (spec §Error Semantics
        // "Error-code compatibility"). Do NOT use `McpError::invalid_params`
        // here — that maps to -32602 and is reserved for JSON-RPC envelope
        // / params-deserialization failures.
        let (port_path, baud) = match (p.port, p.device) {
            (Some(_), Some(_)) => {
                return Ok(tool_error(
                    SerialError::InvalidParam {
                        name: "port/device".into(),
                        reason: "specify 'device' or 'port', not both".into(),
                    },
                    None,
                    false,
                    false,
                ));
            }
            (None, None) => {
                return Ok(tool_error(
                    SerialError::InvalidParam {
                        name: "port/device".into(),
                        reason: "missing required parameter: 'port' or 'device'".into(),
                    },
                    None,
                    false,
                    false,
                ));
            }
            (Some(port), None) => (port, p.baud.unwrap_or(config::DEFAULT_BAUD)),
            (None, Some(device_name)) => {
                let (path, profile_baud) =
                    match crate::serial::resolve_device(&device_name, &self.profiles) {
                        Ok(resolved) => resolved,
                        Err(err) => return Ok(tool_error(err, None, false, false)),
                    };
                (path, p.baud.unwrap_or(profile_baud))
            }
        };

        let timeout_ms = p
            .timeout_ms
            .unwrap_or(config::DEFAULT_TIMEOUT_MS)
            .min(config::MAX_TIMEOUT_MS);

        match self.sessions.open(&port_path, baud, timeout_ms).await {
            Ok(session_id) => structured(OpenResult { session_id }),
            Err(err) => Ok(tool_error(err, None, false, false)),
        }
    }

    #[tool(
        name = "serial.sessions",
        description = "Inspect currently open serial sessions without consuming device input. Useful for recovery after context loss or handoff.",
        output_schema = tool_output_schema::<SessionsResult>(),
        annotations(title = "List serial sessions", read_only_hint = true, destructive_hint = false, idempotent_hint = true, open_world_hint = false)
    )]
    #[instrument(skip(self))]
    pub async fn sessions(&self) -> Result<CallToolResult, McpError> {
        structured(SessionsResult {
            sessions: self.sessions.sessions(),
        })
    }

    #[tool(
        name = "serial.get_session",
        description = "Inspect one open serial session without consuming device input.",
        output_schema = tool_output_schema::<GetSessionResult>(),
        annotations(title = "Get serial session", read_only_hint = true, destructive_hint = false, idempotent_hint = true, open_world_hint = false)
    )]
    #[instrument(skip(self, params), fields(session_id = %params.0.session_id))]
    pub async fn get_session(
        &self,
        params: Parameters<GetSessionParams>,
    ) -> Result<CallToolResult, McpError> {
        let Parameters(p) = params;
        match self.sessions.get_session(&p.session_id) {
            Ok(session) => structured(GetSessionResult { session }),
            Err(err) => Ok(tool_error(err, Some(p.session_id), false, false)),
        }
    }

    /// Write UTF-8 data to the session's port. Caller controls the bytes
    /// — no implicit newline is appended (spec §Non-Goals).
    ///
    /// Sizes above [`config::MAX_WRITE_CHUNK`] are rejected with the
    /// project's pinned `InvalidParam` code (-32008); a runtime
    /// validation, not a domain failure, so the device sees zero bytes.
    /// Returns structured `{"bytes_written": n}`.
    #[tool(
        name = "serial.write",
        description = "Write UTF-8 bytes verbatim to an open serial session. No implicit newline. This mutates external device state and may interact with a privileged shell.",
        output_schema = tool_output_schema::<WriteResult>(),
        annotations(title = "Write serial bytes", read_only_hint = false, destructive_hint = true, idempotent_hint = false, open_world_hint = false)
    )]
    #[instrument(skip(self, params), fields(session_id = %params.0.session_id, len = params.0.data.len()))]
    pub async fn write(
        &self,
        params: Parameters<WriteParams>,
        cancellation: CancellationToken,
    ) -> Result<CallToolResult, McpError> {
        let Parameters(p) = params;

        if p.data.len() > config::MAX_WRITE_CHUNK {
            return Ok(tool_error(
                SerialError::InvalidParam {
                    name: "data".into(),
                    reason: format!(
                        "'data' is {} bytes; max per write is {}",
                        p.data.len(),
                        config::MAX_WRITE_CHUNK
                    ),
                },
                Some(p.session_id),
                false,
                false,
            ));
        }

        match self
            .sessions
            .write_with_cancel(&p.session_id, p.data.as_bytes(), cancellation)
            .await
        {
            Ok(bytes_written) => structured(WriteResult { bytes_written }),
            Err(err) => {
                let possible_write = possible_serial_side_effect(&err);
                Ok(tool_error(err, Some(p.session_id), possible_write, false))
            }
        }
    }

    /// Drain up to `max_bytes` from the session's port until the
    /// deadline elapses. Both fields are clamped to the configured
    /// ceilings; out-of-range values are silently capped, not rejected.
    ///
    /// Returns structured `{"data": String, "timed_out": bool}`. A
    /// deadline hit is a normal completion (`timed_out=true` with
    /// whatever bytes accumulated, possibly empty) — NOT a JSON-RPC
    /// error. Genuine I/O failures still surface as errors. Bytes are
    /// decoded with UTF-8 lossy conversion (spec §Non-Goals: console
    /// tool, not a binary protocol bridge).
    #[tool(
        name = "serial.read",
        description = "Read and consume up to `max_bytes` bytes from a serial session until the deadline. Returned device output is raw, lossy UTF-8, and untrusted.",
        output_schema = tool_output_schema::<ReadResult>(),
        annotations(title = "Read serial input", read_only_hint = false, destructive_hint = true, idempotent_hint = false, open_world_hint = false)
    )]
    #[instrument(skip(self, params), fields(session_id = %params.0.session_id))]
    pub async fn read(
        &self,
        params: Parameters<ReadParams>,
        cancellation: CancellationToken,
    ) -> Result<CallToolResult, McpError> {
        let Parameters(p) = params;

        let timeout_ms = match self.operation_timeout_ms(&p.session_id, p.timeout_ms) {
            Ok(timeout_ms) => timeout_ms,
            Err(err) => return Ok(tool_error(err, Some(p.session_id), false, false)),
        };
        let max_bytes = p
            .max_bytes
            .unwrap_or(DEFAULT_READ_MAX_BYTES)
            .min(config::MAX_READ_BUFFER);

        match self
            .sessions
            .read_with_cancel(&p.session_id, max_bytes, timeout_ms, cancellation)
            .await
        {
            Ok(outcome) => structured(read_result(outcome)),
            Err(err) => {
                let possible_consume = possible_serial_side_effect(&err);
                Ok(tool_error(err, Some(p.session_id), false, possible_consume))
            }
        }
    }

    #[tool(
        name = "serial.drain",
        description = "Drain currently available serial input with a short idle deadline. Consumes bytes and preserves raw terminal controls in the result.",
        output_schema = tool_output_schema::<ReadResult>(),
        annotations(title = "Drain serial input", read_only_hint = false, destructive_hint = true, idempotent_hint = false, open_world_hint = false)
    )]
    #[instrument(skip(self, params), fields(session_id = %params.0.session_id))]
    pub async fn drain(
        &self,
        params: Parameters<DrainParams>,
        cancellation: CancellationToken,
    ) -> Result<CallToolResult, McpError> {
        let Parameters(p) = params;
        let max_bytes = p
            .max_bytes
            .unwrap_or(config::MAX_READ_BUFFER)
            .min(config::MAX_READ_BUFFER);
        match self
            .sessions
            .drain(&p.session_id, max_bytes, cancellation)
            .await
        {
            Ok(outcome) => structured(read_result(outcome)),
            Err(err) => {
                let possible_consume = possible_serial_side_effect(&err);
                Ok(tool_error(err, Some(p.session_id), false, possible_consume))
            }
        }
    }

    #[tool(
        name = "serial.clear_input",
        description = "Discard currently available serial input with a short idle deadline. Returns byte counts and status but not the discarded data.",
        output_schema = tool_output_schema::<ClearInputResult>(),
        annotations(title = "Clear serial input", read_only_hint = false, destructive_hint = true, idempotent_hint = false, open_world_hint = false)
    )]
    #[instrument(skip(self, params), fields(session_id = %params.0.session_id))]
    pub async fn clear_input(
        &self,
        params: Parameters<DrainParams>,
        cancellation: CancellationToken,
    ) -> Result<CallToolResult, McpError> {
        let Parameters(p) = params;
        let max_bytes = p
            .max_bytes
            .unwrap_or(config::MAX_READ_BUFFER)
            .min(config::MAX_READ_BUFFER);
        match self
            .sessions
            .clear_input(&p.session_id, max_bytes, cancellation)
            .await
        {
            Ok(outcome) => structured(ClearInputResult {
                status: outcome.status.as_str(),
                bytes_read: outcome.bytes_read,
                discarded_bytes: outcome.data.len(),
                truncated: outcome.truncated,
                session_usable: true,
            }),
            Err(err) => {
                let possible_consume = possible_serial_side_effect(&err);
                Ok(tool_error(err, Some(p.session_id), false, possible_consume))
            }
        }
    }

    /// Read until `pattern` matches (regex) or `timeout_ms` elapses.
    /// Partial output is **not** an error: timeout/EOF returns the
    /// buffered data with `matched=false` (spec §Error Semantics —
    /// "partial output is normal completion"). Invalid or empty regex
    /// is rejected with `InvalidParam` (-32008) *before* any port read,
    /// so the device stream is not consumed on bad input.
    ///
    /// Returns structured `{"data": String, "matched": bool}`.
    #[tool(
        name = "serial.read_until",
        description = "Read and consume serial input until a regex matches or timeout elapses. Raw output may include command echoes, prompts, ANSI/OSC controls, and untrusted device text.",
        output_schema = tool_output_schema::<ReadUntilResult>(),
        annotations(title = "Read serial until match", read_only_hint = false, destructive_hint = true, idempotent_hint = false, open_world_hint = false)
    )]
    #[instrument(skip(self, params), fields(session_id = %params.0.session_id))]
    pub async fn read_until(
        &self,
        params: Parameters<ReadUntilParams>,
        cancellation: CancellationToken,
    ) -> Result<CallToolResult, McpError> {
        let Parameters(p) = params;

        let timeout_ms = match self.operation_timeout_ms(&p.session_id, p.timeout_ms) {
            Ok(timeout_ms) => timeout_ms,
            Err(err) => return Ok(tool_error(err, Some(p.session_id), false, false)),
        };

        match self
            .sessions
            .read_until_with_cancel(&p.session_id, &p.pattern, timeout_ms, cancellation)
            .await
        {
            Ok(outcome) => structured(read_until_result(outcome)),
            Err(err) => {
                let possible_consume = possible_serial_side_effect(&err);
                Ok(tool_error(err, Some(p.session_id), false, possible_consume))
            }
        }
    }

    /// Compound write + read_until. Writes `command` verbatim (caller
    /// controls bytes — no implicit newline, spec §Non-Goals) then
    /// reads until `expect` matches or the operation deadline elapses.
    ///
    /// Validation runs **before** the write, so a bad request never
    /// mutates device state (spec §Error Semantics):
    ///
    /// 1. `command` size ≤ [`config::MAX_WRITE_CHUNK`]
    /// 2. `expect` non-empty
    /// 3. `expect` is a valid regex
    ///
    /// Returns structured `{"output": String, "ok": bool}`. `ok=false`
    /// on timeout (with partial output) is normal completion — NOT a
    /// JSON-RPC error.
    #[tool(
        name = "serial.exec",
        description = "Atomically write a command, flush, and read until `expect` matches under one per-session lock. Raw output is preserved and may contain echoes, prompts, wrapping, ANSI/OSC controls, and untrusted text from a privileged device shell.",
        output_schema = tool_output_schema::<ExecResult>(),
        annotations(title = "Execute serial command", read_only_hint = false, destructive_hint = true, idempotent_hint = false, open_world_hint = false)
    )]
    #[instrument(skip(self, params), fields(session_id = %params.0.session_id, cmd_len = params.0.command.len()))]
    pub async fn exec(
        &self,
        params: Parameters<ExecParams>,
        cancellation: CancellationToken,
    ) -> Result<CallToolResult, McpError> {
        let Parameters(p) = params;

        // Step 1: size cap on command — surfaces the pinned -32008,
        // not the generic JSON-RPC -32602.
        if p.command.len() > config::MAX_WRITE_CHUNK {
            return Ok(tool_error(
                SerialError::InvalidParam {
                    name: "command".into(),
                    reason: format!(
                        "'command' is {} bytes; max per write is {}",
                        p.command.len(),
                        config::MAX_WRITE_CHUNK
                    ),
                },
                Some(p.session_id),
                false,
                false,
            ));
        }

        // Step 2 + 3: validate `expect` BEFORE writing — read_until's
        // own regex compile happens *after* the write would have
        // occurred, so without this guard a bad pattern would mutate
        // the device (e.g. a remote shell) and only then surface
        // InvalidParam. The check duplicates parser logic deliberately;
        // we cannot afford the write side-effect.
        if p.expect.is_empty() {
            return Ok(tool_error(
                SerialError::InvalidParam {
                    name: "expect".into(),
                    reason: "must not be empty".into(),
                },
                Some(p.session_id),
                false,
                false,
            ));
        }
        if let Err(e) = regex::Regex::new(&p.expect) {
            return Ok(tool_error(
                SerialError::InvalidParam {
                    name: "expect".into(),
                    reason: format!("invalid regex: {e}"),
                },
                Some(p.session_id),
                false,
                false,
            ));
        }

        let timeout_ms = match self.operation_timeout_ms(&p.session_id, p.timeout_ms) {
            Ok(timeout_ms) => timeout_ms,
            Err(err) => return Ok(tool_error(err, Some(p.session_id), false, false)),
        };

        match self
            .sessions
            .exec(
                &p.session_id,
                p.command.as_bytes(),
                &p.expect,
                timeout_ms,
                p.clear_before_write.unwrap_or(false),
                cancellation,
            )
            .await
        {
            Ok(outcome) => structured(exec_result(outcome, p.normalize_output.unwrap_or(false))),
            Err(err) => {
                let possible_write = possible_serial_side_effect(&err);
                Ok(tool_error(
                    err,
                    Some(p.session_id),
                    possible_write,
                    possible_write,
                ))
            }
        }
    }

    /// Close a session and release its port. Removes the session from
    /// the manager's map; subsequent reads/writes on the same id return
    /// [`crate::errors::SerialError::SessionNotFound`] (-32003).
    ///
    /// Returns structured `{"ok": true}` on success.
    #[tool(
        name = "serial.close",
        description = "Close a serial session and release its port. Does not cancel already checked-out in-flight serial I/O in this version.",
        output_schema = tool_output_schema::<CloseResult>(),
        annotations(title = "Close serial session", read_only_hint = false, destructive_hint = true, idempotent_hint = false, open_world_hint = false)
    )]
    #[instrument(skip(self, params), fields(session_id = %params.0.session_id))]
    pub async fn close(&self, params: Parameters<CloseParams>) -> Result<CallToolResult, McpError> {
        let Parameters(p) = params;
        match self.sessions.close(&p.session_id).await {
            Ok(()) => structured(CloseResult { ok: true }),
            Err(err) => Ok(tool_error(err, Some(p.session_id), false, false)),
        }
    }

    fn operation_timeout_ms(
        &self,
        session_id: &str,
        requested: Option<u64>,
    ) -> Result<u64, SerialError> {
        match requested {
            Some(timeout_ms) => Ok(timeout_ms.min(config::MAX_TIMEOUT_MS)),
            None => Ok(self.sessions.get_session(session_id)?.default_timeout_ms),
        }
    }
}

/// Default `max_bytes` for `serial.read` when the caller omits the field.
/// Kept local to the rmcp adapter so the constant does not leak into the
/// public domain config surface.
const DEFAULT_READ_MAX_BYTES: usize = 4096;

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct ListPortsResult {
    pub ports: Vec<crate::serial::PortDescriptor>,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct OpenResult {
    pub session_id: String,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct SessionsResult {
    pub sessions: Vec<SessionSnapshot>,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct GetSessionResult {
    pub session: SessionSnapshot,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct WriteResult {
    pub bytes_written: usize,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct ReadResult {
    pub data: String,
    pub status: &'static str,
    pub timed_out: bool,
    pub bytes_read: usize,
    pub truncated: bool,
    pub session_usable: bool,
    pub output_is_untrusted: bool,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct ClearInputResult {
    pub status: &'static str,
    pub bytes_read: usize,
    pub discarded_bytes: usize,
    pub truncated: bool,
    pub session_usable: bool,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct ReadUntilResult {
    pub data: String,
    pub matched: bool,
    pub status: &'static str,
    pub bytes_read: usize,
    pub truncated: bool,
    pub match_details: Option<MatchDetailsResult>,
    pub session_usable: bool,
    pub output_is_untrusted: bool,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct ExecResult {
    pub status: &'static str,
    pub output: String,
    pub raw_output: String,
    pub normalized_output: Option<String>,
    pub ok: bool,
    pub bytes_written: usize,
    pub bytes_read: usize,
    pub elapsed_ms: u128,
    pub truncated: bool,
    pub match_details: Option<MatchDetailsResult>,
    pub command_written: bool,
    pub session_usable: bool,
    pub cleared_before_write: Option<ClearInputResult>,
    pub output_is_untrusted: bool,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct MatchDetailsResult {
    pub text: String,
    pub start_byte: usize,
    pub end_byte: usize,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct CloseResult {
    pub ok: bool,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct ToolErrorResult {
    pub error: ToolErrorBody,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct ToolErrorBody {
    pub r#type: &'static str,
    pub message: String,
    pub code: i32,
    pub data: Value,
    pub retryable: bool,
    pub session_id: Option<String>,
    pub command_written: bool,
    pub bytes_consumed: bool,
    pub session_usable: bool,
}

fn tool_output_schema<T: JsonSchema + std::any::Any>() -> Arc<JsonObject> {
    let mut success_schema = rmcp::handler::server::tool::schema_for_type::<T>()
        .as_ref()
        .clone();
    let mut error_schema = rmcp::handler::server::tool::schema_for_type::<ToolErrorResult>()
        .as_ref()
        .clone();
    let mut defs = JsonObject::new();
    drain_defs(&mut success_schema, &mut defs);
    drain_defs(&mut error_schema, &mut defs);

    let mut root = JsonObject::new();
    root.insert("type".to_string(), json!("object"));
    root.insert(
        "anyOf".to_string(),
        json!([Value::Object(success_schema), Value::Object(error_schema)]),
    );
    if !defs.is_empty() {
        root.insert("$defs".to_string(), Value::Object(defs));
    }
    Arc::new(root)
}

fn drain_defs(schema: &mut JsonObject, defs: &mut JsonObject) {
    if let Some(Value::Object(schema_defs)) = schema.remove("$defs") {
        for (key, value) in schema_defs {
            defs.insert(key, value);
        }
    }
}

fn structured<T: Serialize>(value: T) -> Result<CallToolResult, McpError> {
    Ok(CallToolResult::structured(
        serde_json::to_value(value).expect("tool result must serialize"),
    ))
}

fn tool_error(
    err: SerialError,
    session_id: Option<String>,
    command_written: bool,
    bytes_consumed: bool,
) -> CallToolResult {
    // Invariant: `session_usable => session_id present`. A failure with no
    // session id (e.g. open-time InvalidParam / PortBusy / DeviceNotFound)
    // never created a session, so it can never be "usable".
    let session_usable = session_id.is_some()
        && !matches!(
            err,
            SerialError::SessionNotFound { .. }
                | SerialError::InvalidState { .. }
                | SerialError::Io { .. }
        );
    CallToolResult::structured_error(
        serde_json::to_value(ToolErrorResult {
            error: ToolErrorBody {
                r#type: err.type_name(),
                message: err.to_string(),
                code: err.code(),
                data: err.data(),
                retryable: err.retryable(),
                session_id,
                command_written,
                bytes_consumed,
                session_usable,
            },
        })
        .expect("tool error must serialize"),
    )
}

fn possible_serial_side_effect(err: &SerialError) -> bool {
    matches!(
        err,
        SerialError::Io { .. } | SerialError::Timeout { .. } | SerialError::Cancelled
    )
}

fn read_result(outcome: ReadOutcome) -> ReadResult {
    let status = outcome.status.as_str();
    ReadResult {
        data: String::from_utf8_lossy(&outcome.data).into_owned(),
        status,
        timed_out: status == "timed_out",
        bytes_read: outcome.bytes_read,
        truncated: outcome.truncated,
        session_usable: true,
        output_is_untrusted: true,
    }
}

fn read_until_result(outcome: ExecOutcome) -> ReadUntilResult {
    let status = outcome.status.as_str();
    ReadUntilResult {
        data: String::from_utf8_lossy(&outcome.output).into_owned(),
        matched: status == "matched",
        status,
        bytes_read: outcome.bytes_read,
        truncated: outcome.truncated,
        match_details: outcome.match_details.map(match_details_result),
        session_usable: outcome.session_usable,
        output_is_untrusted: true,
    }
}

fn exec_result(outcome: ExecOutcome, normalize_output: bool) -> ExecResult {
    let raw_output = String::from_utf8_lossy(&outcome.output).into_owned();
    let normalized_output = normalize_output.then(|| normalize_terminal_output(&raw_output));
    let status = outcome.status.as_str();
    ExecResult {
        status,
        output: raw_output.clone(),
        raw_output,
        normalized_output,
        ok: status == "matched",
        bytes_written: outcome.bytes_written,
        bytes_read: outcome.bytes_read,
        elapsed_ms: outcome.elapsed_ms,
        truncated: outcome.truncated,
        match_details: outcome.match_details.map(match_details_result),
        command_written: outcome.command_written,
        session_usable: outcome.session_usable,
        cleared_before_write: outcome.cleared_before_write.map(|o| ClearInputResult {
            status: o.status.as_str(),
            bytes_read: o.bytes_read,
            discarded_bytes: o.data.len(),
            truncated: o.truncated,
            session_usable: true,
        }),
        output_is_untrusted: true,
    }
}

fn match_details_result(details: crate::serial::parser::MatchDetails) -> MatchDetailsResult {
    MatchDetailsResult {
        text: details.text,
        start_byte: details.start_byte,
        end_byte: details.end_byte,
    }
}

fn normalize_terminal_output(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    let mut chars = raw.chars().peekable();
    while let Some(ch) = chars.next() {
        if ch == '\u{1b}' {
            match chars.peek().copied() {
                Some(']') => {
                    let _ = chars.next();
                    let mut prev_esc = false;
                    for c in chars.by_ref() {
                        if c == '\u{7}' || (prev_esc && c == '\\') {
                            break;
                        }
                        prev_esc = c == '\u{1b}';
                    }
                }
                Some('[') => {
                    let _ = chars.next();
                    for c in chars.by_ref() {
                        if ('@'..='~').contains(&c) {
                            break;
                        }
                    }
                }
                _ => {}
            }
        } else if ch != '\r' {
            out.push(ch);
        }
    }
    out
}

/// Input for `serial.open`. The XOR between `port` and `device` is
/// validated at runtime rather than via schema, so the contract stays a
/// single tool with two mutually exclusive entry points.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct OpenParams {
    /// Literal device path (e.g. `/dev/ttyUSB0`). Mutually exclusive
    /// with `device`.
    #[serde(default)]
    pub port: Option<String>,
    /// Named device profile from `devices.toml`. Mutually exclusive
    /// with `port`.
    #[serde(default)]
    pub device: Option<String>,
    /// Override the baud rate. Defaults to the profile baud (device
    /// path) or `config::DEFAULT_BAUD` (port path).
    #[serde(default)]
    pub baud: Option<u32>,
    /// Per-session default operation timeout in milliseconds. Clamped
    /// to `config::MAX_TIMEOUT_MS`. Falls back to
    /// `config::DEFAULT_TIMEOUT_MS` when absent.
    #[serde(default)]
    pub timeout_ms: Option<u64>,
}

/// Input for `serial.write`. `data` is UTF-8 text; binary protocols are
/// out of scope (spec §Non-Goals).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct WriteParams {
    pub session_id: String,
    pub data: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct GetSessionParams {
    pub session_id: String,
}

/// Input for `serial.read`. Both bounds are optional; the handler
/// applies defaults and clamps to the configured ceilings.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ReadParams {
    pub session_id: String,
    /// Soft cap on bytes returned. Clamped to `config::MAX_READ_BUFFER`.
    /// Defaults to `DEFAULT_READ_MAX_BYTES` when absent.
    #[serde(default)]
    pub max_bytes: Option<usize>,
    /// Read deadline in milliseconds. Clamped to `config::MAX_TIMEOUT_MS`.
    /// Defaults to the session timeout from `serial.open` when absent.
    #[serde(default)]
    pub timeout_ms: Option<u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct DrainParams {
    pub session_id: String,
    #[serde(default)]
    pub max_bytes: Option<usize>,
}

/// Input for `serial.read_until`. `pattern` is a regex string compiled
/// by the parser before any port read; invalid or empty patterns fail
/// validation up-front.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ReadUntilParams {
    pub session_id: String,
    pub pattern: String,
    /// Read deadline in milliseconds. Clamped to `config::MAX_TIMEOUT_MS`.
    /// Defaults to the session timeout from `serial.open` when absent.
    #[serde(default)]
    pub timeout_ms: Option<u64>,
}

/// Input for `serial.close`. Just the session id — closing is
/// idempotent only with respect to "already-removed sessions" (those
/// produce SessionNotFound, the same code an unknown id would).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct CloseParams {
    pub session_id: String,
}

/// Input for `serial.exec`. `command` is written verbatim (no implicit
/// newline). `expect` is a non-empty regex compiled BEFORE the write so
/// invalid input never mutates device state.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ExecParams {
    pub session_id: String,
    pub command: String,
    pub expect: String,
    #[serde(default)]
    pub clear_before_write: Option<bool>,
    #[serde(default)]
    pub normalize_output: Option<bool>,
    /// Whole-operation deadline in milliseconds. Clamped to
    /// `config::MAX_TIMEOUT_MS`. Defaults to the session timeout from
    /// `serial.open` when absent.
    #[serde(default)]
    pub timeout_ms: Option<u64>,
}

#[tool_handler(router = self.tool_router)]
impl<B: SerialBackend> ServerHandler for McpServer<B> {
    /// Override the macro-generated `call_tool` so the rmcp dispatch
    /// has a single chokepoint for the tool-call journal (spec
    /// §Journal Requirements). Lifecycle
    /// methods (`initialize`, `tools/list`, `notifications/initialized`)
    /// never enter this method — they are handled elsewhere in the
    /// SDK — so narrowing to "tool calls only" falls out of the choice
    /// of hook point, not a name filter.
    ///
    /// One `call` row goes in before dispatch and one `result` row
    /// after, regardless of outcome. Journal I/O is wrapped in
    /// `JournalWriter::log` which warns-and-swallows on failure, so
    /// audit pressure never blocks tool execution. Concurrent calls
    /// stay non-interleaving via the writer's `tokio::sync::Mutex`.
    async fn call_tool(
        &self,
        request: CallToolRequestParams,
        context: RequestContext<rmcp::RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        // Capture the inputs we need for journaling BEFORE moving
        // `request` into the SDK's ToolCallContext.
        let tool_name = request.name.to_string();
        let args_value: Value = request
            .arguments
            .as_ref()
            .map(|m| Value::Object(m.clone()))
            .unwrap_or(Value::Null);

        // call row
        if let Some(j) = &self.journal {
            let entry = JournalEntry::new(
                journal::call_session_id(&args_value),
                tool_name.clone(),
                JournalEntry::DIR_CALL,
                journal::call_summary(&tool_name, &args_value),
            );
            j.log(&entry).await;
        }

        let tcc = rmcp::handler::server::tool::ToolCallContext::new(self, request, context);
        let result = self.tool_router.call(tcc).await;

        // result row
        if let Some(j) = &self.journal {
            let result_ref: Result<&CallToolResult, &McpError> = result.as_ref();
            let entry = JournalEntry::new(
                journal::result_session_id(&tool_name, &args_value, &result_ref),
                tool_name.clone(),
                JournalEntry::DIR_RESULT,
                journal::result_summary(&tool_name, &result_ref),
            );
            j.log(&entry).await;
        }

        result
    }

    fn get_info(&self) -> ServerInfo {
        // `ServerInfo`/`InitializeResult` is `#[non_exhaustive]`, so we
        // start from `default()` (already pinned to the latest protocol
        // version) and overwrite only what we care about. Constructing it
        // directly with a struct-update expression is rejected by rustc.
        //
        // We construct `Implementation` explicitly instead of calling
        // `Implementation::from_build_env()`. That helper expands its
        // `env!("CARGO_PKG_*")` reads at the rmcp crate's build site, so
        // it would report `name = "rmcp"` here. We want our crate's
        // identity to reach the client.
        let mut info = ServerInfo::default();
        info.capabilities = ServerCapabilities::builder().enable_tools().build();
        info.server_info = Implementation::new(env!("CARGO_PKG_NAME"), env!("CARGO_PKG_VERSION"));
        info
    }
}

#[cfg(test)]
mod tool_error_tests {
    use super::tool_error;
    use crate::errors::SerialError;

    /// Extract `error.session_usable` from a `tool_error` result.
    fn session_usable(err: SerialError, session_id: Option<String>) -> bool {
        let result = tool_error(err, session_id, false, false);
        assert_eq!(result.is_error, Some(true), "tool_error must set isError");
        result
            .structured_content
            .expect("structured error content")
            .get("error")
            .and_then(|e| e.get("session_usable"))
            .and_then(|v| v.as_bool())
            .expect("session_usable bool")
    }

    // Invariant: `session_usable => session_id present`. Open-time failures
    // carry no session id and must never claim the session is usable.
    #[test]
    fn open_invalid_param_without_session_is_not_usable() {
        assert!(!session_usable(
            SerialError::InvalidParam {
                name: "port/device".into(),
                reason: "specify one".into(),
            },
            None,
        ));
    }

    #[test]
    fn port_busy_without_session_is_not_usable() {
        assert!(!session_usable(
            SerialError::PortBusy {
                port: "/dev/ttyUSB0".into(),
            },
            None,
        ));
    }

    #[test]
    fn device_not_found_without_session_is_not_usable() {
        assert!(!session_usable(
            SerialError::DeviceNotFound {
                device: "unknown".into(),
            },
            None,
        ));
    }

    #[test]
    fn recoverable_op_error_with_session_stays_usable() {
        assert!(session_usable(
            SerialError::Timeout { timeout_ms: 1_000 },
            Some("0123456789abcdef0123456789abcdef".into()),
        ));
    }

    #[test]
    fn session_not_found_with_session_is_unusable() {
        assert!(!session_usable(
            SerialError::SessionNotFound {
                session_id: "sid".into(),
            },
            Some("sid".into()),
        ));
    }
}
